### ISSUE TITLE
Bad links on the paper

### ISSUE THREAD

**Issue by vfdev-5** [valeoai/BUDA#1]
Hi, 
currently, links on the paper are not properly setup. Please, update them.
Thanks

**Comment by maximebucher** [comment]
Hi,
fixed 

Maxime

**Comment by vfdev-5** [comment]
Hi Maxime, thanks for the update. Very interesting paper!
When you plan to release the code for that ?

Looking at additional qualitatives results on MS-COCO, it seems like there can be the cases where ZS3Net could predict a little bit more accurately than BudaNet. However, we do not see this on the metrics. Is this image is a very particular example ?
Thanks

<img width="590" alt="Screen Shot 2020-04-03 at 11 40 35" src="https://user-images.githubusercontent.com/2459423/78347062-2db0cc80-75a0-11ea-9e91-f61cfd08190e.png">
