### ISSUE TITLE
Difference with UODR

### ISSUE THREAD

**Issue by cuishuhao** [valeoai/BUDA#2]
hi!
I did not find differences between the tasks of BUDA and ["UODR"](http://openaccess.thecvf.com/content_CVPR_2019/papers/Zhuo_Unsupervised_Open_Domain_Recognition_by_Semantic_Discrepancy_Minimization_CVPR_2019_paper.pdf).
Could you please tell the differences?
Thank you!

**Comment by maximebucher** [comment]
Hi,
thank you for bringing this relevant reference to our attention. We will discuss this work in a further version of our arXiv paper.
Maxime
